/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package engtelecom.swingType;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author faber222
 */
public class CapabilityProfile extends javax.swing.JFrame {

    // Variables declaration - do not modify
    private javax.swing.JButton jButtonONUCapaAplicar;

    private javax.swing.JButton jButtonONUCapaCancel;

    private javax.swing.JComboBox<String> jComboBoxCPEType;

    private javax.swing.JComboBox<String> jComboBoxPONType;

    private javax.swing.JComboBox<String> jComboBoxWifiNumber;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner10GPort;
    private javax.swing.JSpinner jSpinner1GPort;
    private javax.swing.JSpinner jSpinnerPOTSNumber;
    private javax.swing.JSpinner jSpinnerUSBNumber;
    private javax.swing.JTextField jTextFieldEquipamentID;
    private javax.swing.JTextField jTextFieldProfileName;
    private final SpinnerNumberModel model;
    private final SpinnerNumberModel model2;
    private final SpinnerNumberModel model3;
    private final SpinnerNumberModel model4;
    private final String[] cpeType;
    private final String[] ponType;
    private final String[] wifiNumber;

    private final String[] indexPonType;
    private CapabilityProfileListener listener;

    // End of variables declaration
    /**
     * Creates new form CapabilityProfile2
     */
    public CapabilityProfile(final String[] cpeType, final String[] ponType, final String[] indexPonType,
            final String[] wifiNumber) {
        this.cpeType = cpeType;
        this.ponType = ponType;
        this.indexPonType = indexPonType;
        this.wifiNumber = wifiNumber;
        this.model = new SpinnerNumberModel(0, 0, 100, 1);
        this.model2 = new SpinnerNumberModel(0, 0, 100, 1);
        this.model3 = new SpinnerNumberModel(0, 0, 100, 1);
        this.model4 = new SpinnerNumberModel(0, 0, 100, 1);
        initComponents();
    }

    public void setListener(final CapabilityProfileListener listener) {
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProfileName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCPEType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPONType = new javax.swing.JComboBox<>();
        jTextFieldEquipamentID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxWifiNumber = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1GPort = new javax.swing.JSpinner(this.model);
        jSpinner10GPort = new javax.swing.JSpinner(this.model2);
        jSpinnerPOTSNumber = new javax.swing.JSpinner(this.model3);
        jSpinnerUSBNumber = new javax.swing.JSpinner(this.model4);
        jButtonONUCapaCancel = new javax.swing.JButton();
        jButtonONUCapaAplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create a ONU Capability Profile");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setToolTipText("Create a ONU Capability Profile");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setText("Profile Name:");

        jTextFieldProfileName.setText("HG6145D2");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("CPE Type(X):");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("CPE EQ ID");

        jComboBoxCPEType.setModel(
                new javax.swing.DefaultComboBoxModel<>(this.cpeType));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("PON Type(X):");

        jComboBoxPONType.setModel(new javax.swing.DefaultComboBoxModel<>(this.ponType));
        jComboBoxPONType.setSelectedIndex(3);

        jTextFieldEquipamentID.setText("HG6145D2");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Wifi Number:");

        jComboBoxWifiNumber.setModel(
                new javax.swing.DefaultComboBoxModel<>(this.wifiNumber));
        jComboBoxWifiNumber.setSelectedIndex(2);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Port Setting",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("100M/1000M LAN Number (Y):");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setText("POTS Number:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setText("10G LAN Number:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel9.setText("USB Number (Z):");

        final javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING,
                                        false)
                                        .addComponent(jLabel6,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel7,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING,
                                        false)
                                        .addComponent(jSpinner1GPort,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                80, Short.MAX_VALUE)
                                        .addComponent(jSpinnerPOTSNumber))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                110,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8,
                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING,
                                        false)
                                        .addComponent(jSpinner10GPort,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                80, Short.MAX_VALUE)
                                        .addComponent(jSpinnerUSBNumber))
                                .addGap(6, 6, 6)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jSpinner1GPort,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSpinner10GPort,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jSpinnerPOTSNumber,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jSpinnerUSBNumber,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        jButtonONUCapaCancel.setText("Cancel");

        jButtonONUCapaCancel.addActionListener(this::jButtonONUCapaCancelActionPerformed);

        jButtonONUCapaAplicar.setText("Apply");
        jButtonONUCapaAplicar.addActionListener(this::jButtonONUCapaAplicarActionPerformed);

        final javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout
                                                .createSequentialGroup()
                                                .addComponent(jButtonONUCapaAplicar)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonONUCapaCancel))
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        false)
                                                .addComponent(jPanel2,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout
                                                        .createSequentialGroup()
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel1)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel2))
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addGroup(jPanel1Layout
                                                                        .createSequentialGroup()
                                                                        .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        false)
                                                                                .addComponent(jComboBoxCPEType,
                                                                                        0,
                                                                                        200,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(jTextFieldEquipamentID))
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel5))
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jComboBoxWifiNumber,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        200,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jComboBoxPONType,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        200,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addComponent(jTextFieldProfileName)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextFieldProfileName,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jComboBoxCPEType,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4)
                                                .addComponent(jComboBoxPONType,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING,
                                        false)
                                        .addComponent(jLabel3)
                                        .addComponent(jComboBoxWifiNumber,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldEquipamentID)
                                        .addComponent(jLabel5))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonONUCapaCancel)
                                        .addComponent(jButtonONUCapaAplicar))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE));

        jPanel1.getAccessibleContext().setAccessibleName("Create a ONU Capability Profile");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void jButtonONUCapaAplicarActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonONUCapaAplicarActionPerformed
        final String cpeType1 = String.valueOf(jComboBoxCPEType.getSelectedIndex());
        final String ponType1 = indexPonType[(jComboBoxPONType.getSelectedIndex())];
        final String wifiNumber1 = jComboBoxWifiNumber.getSelectedItem().toString();

        final String tenGPort = jSpinner10GPort.getValue().toString();
        final String oneGPort = jSpinner1GPort.getValue().toString();
        final String potsNumber = jSpinnerPOTSNumber.getValue().toString();
        final String usbNumber = jSpinnerUSBNumber.getValue().toString();

        final String equipamentID = jTextFieldEquipamentID.getText();
        final String profileName = jTextFieldProfileName.getText();

        if (listener != null) {
            listener.onProfileCreated(cpeType1, ponType1, wifiNumber1,
                    tenGPort, oneGPort, equipamentID,
                    potsNumber, profileName, usbNumber);
            this.dispose(); // Fecha o JFrame
        }
    }// GEN-LAST:event_jButtonONUCapaAplicarActionPerformed

    private void jButtonONUCapaCancelActionPerformed(final java.awt.event.ActionEvent evt) {
        this.dispose();
    }

}
