/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package engtelecom.swingType;

/**
 *
 * @author faber222
 */
public class CapabilityProfile extends javax.swing.JFrame {

    /**
     * Creates new form CapabilityProfile2
     */
    public CapabilityProfile(String[] cpeType, String[] ponType, String[] wifiNumber) {
        this.cpeType = cpeType;
        this.ponType = ponType;
        this.wifiNumber = wifiNumber;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProfileName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCPEType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPONType = new javax.swing.JComboBox<>();
        jTextFieldEquipamentID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxWifiNumber = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1GPort = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPOTSNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField10GPort = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldUSBNumber = new javax.swing.JTextField();
        jButtonONUCapaCancel = new javax.swing.JButton();
        jButtonONUCapaAplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create a ONU Capability Profile");
        setAlwaysOnTop(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setToolTipText("Create a ONU Capability Profile");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setText("Profile Name:");

        jTextFieldProfileName.setText("HG6145D2");
        jTextFieldProfileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProfileNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("CPE Type(X):");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("CPE EQ ID");

        jComboBoxCPEType.setModel(
                new javax.swing.DefaultComboBoxModel<>(this.cpeType));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("PON Type(X):");

        jComboBoxPONType.setModel(new javax.swing.DefaultComboBoxModel<>(this.ponType));
        jComboBoxPONType.setSelectedIndex(3);

        jTextFieldEquipamentID.setText("HG6145D2");
        jTextFieldEquipamentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEquipamentIDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Wifi Number:");

        jComboBoxWifiNumber.setModel(
                new javax.swing.DefaultComboBoxModel<>(this.wifiNumber));
        jComboBoxWifiNumber.setSelectedIndex(2);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Port Setting",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Dialog", 1, 11))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("100M/1000M LAN Number (Y):");

        jTextField1GPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1GPortActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setText("POTS Number:");

        jTextFieldPOTSNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPOTSNumberActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setText("10G LAN Number:");

        jTextField10GPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10GPortActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel9.setText("USB Number (Z):");

        jTextFieldUSBNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUSBNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldPOTSNumber)
                                        .addComponent(jTextField1GPort,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                135,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jPanel2Layout
                                                .createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(17, 17, 17)))
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(jTextFieldUSBNumber,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                135,
                                                Short.MAX_VALUE)
                                        .addComponent(jTextField10GPort))
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(jTextField1GPort,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel8)
                                        .addComponent(jTextField10GPort,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldUSBNumber,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextFieldPOTSNumber,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        jButtonONUCapaCancel.setText("Cancel");

        jButtonONUCapaAplicar.setText("Apply");
        jButtonONUCapaAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonONUCapaAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout
                                                .createSequentialGroup()
                                                .addContainerGap(
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel2,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                        .addGroup(jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addGroup(jPanel1Layout
                                                                        .createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel2))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout
                                                                        .createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout
                                                                                .createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                        .addComponent(jComboBoxCPEType,
                                                                                                0,
                                                                                                200,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(
                                                                                                jTextFieldEquipamentID))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        45,
                                                                                        Short.MAX_VALUE)
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                        .addComponent(
                                                                                                jComboBoxWifiNumber,
                                                                                                0,
                                                                                                200,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(jComboBoxPONType,
                                                                                                0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)))
                                                                        .addComponent(jTextFieldProfileName)))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout
                                                        .createSequentialGroup()
                                                        .addContainerGap(
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jButtonONUCapaAplicar)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButtonONUCapaCancel)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextFieldProfileName,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jComboBoxCPEType,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxPONType,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(jLabel3)
                                        .addComponent(jComboBoxWifiNumber,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldEquipamentID)
                                        .addComponent(jLabel5))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonONUCapaCancel)
                                        .addComponent(jButtonONUCapaAplicar))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE));

        jPanel1.getAccessibleContext().setAccessibleName("Create a ONU Capability Profile");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProfileNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldProfileNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldProfileNameActionPerformed

    private void jTextFieldEquipamentIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldEquipamentIDActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldEquipamentIDActionPerformed

    private void jTextField1GPortActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1GPortActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1GPortActionPerformed

    private void jTextFieldPOTSNumberActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldPOTSNumberActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldPOTSNumberActionPerformed

    private void jTextField10GPortActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField10GPortActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField10GPortActionPerformed

    private void jTextFieldUSBNumberActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldUSBNumberActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldUSBNumberActionPerformed

    private void jButtonONUCapaAplicarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonONUCapaAplicarActionPerformed

        String cpeType1 = jComboBoxCPEType.getSelectedItem().toString();
        String ponType1 = jComboBoxPONType.getSelectedItem().toString();
        String wifiNumber1 = jComboBoxWifiNumber.getSelectedItem().toString();
        String tenGPort = jTextField10GPort.getText();
        String oneGPort = jTextField1GPort.getText();
        String equipamentID = jTextFieldEquipamentID.getText();
        String potsNumber = jTextFieldPOTSNumber.getText();
        String profileName = jTextFieldProfileName.getText();
        String usbNumber = jTextFieldUSBNumber.getText();

        if (listener != null) {
            listener.onProfileCreated(cpeType1, ponType1, wifiNumber1,
                    tenGPort, oneGPort, equipamentID,
                    potsNumber, profileName, usbNumber);
            this.dispose(); // Fecha o JFrame
        }
    }// GEN-LAST:event_jButtonONUCapaAplicarActionPerformed

    public void setListener(CapabilityProfileListener listener) {
        this.listener = listener;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonONUCapaAplicar;
    private javax.swing.JButton jButtonONUCapaCancel;
    private javax.swing.JComboBox<String> jComboBoxCPEType;
    private javax.swing.JComboBox<String> jComboBoxPONType;
    private javax.swing.JComboBox<String> jComboBoxWifiNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField10GPort;
    private javax.swing.JTextField jTextField1GPort;
    private javax.swing.JTextField jTextFieldEquipamentID;
    private javax.swing.JTextField jTextFieldPOTSNumber;
    private javax.swing.JTextField jTextFieldProfileName;
    private javax.swing.JTextField jTextFieldUSBNumber;

    private CapabilityProfileListener listener;
    private String[] cpeType;
    private String[] ponType;
    private String[] wifiNumber;
    // End of variables declaration//GEN-END:variables
}
