/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package engtelecom.swingType;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;
import javax.swing.filechooser.FileNameExtensionFilter;

import engtelecom.access.Telnet;
import engtelecom.product.OltGpon;
import engtelecom.product.OltGponAN5k;

/**
 *
 * @author faber222
 */
public class OltAN5k extends javax.swing.JInternalFrame implements CapabilityProfileListener {

	/**
	 * Creates new form OltG16
	 */
	public OltAN5k() {
		this.model = new SpinnerNumberModel(0, 0, 100, 1);
		this.model2 = new SpinnerNumberModel(0, 0, 100, 1);
		this.model3 = new SpinnerNumberModel(0, 0, 128, 1);
		initComponents();
		oltGponAN5k = new OltGponAN5k();
		capa = new CapabilityProfile(this.cpeType, this.ponType, this.wifiNumber);
	}

	public void previewText() {
		// Tente abrir e ler o arquivo

		try (BufferedReader br = new BufferedReader(new FileReader(this.nomeArq))) {
			StringBuilder content = new StringBuilder();
			String line;

			// Lê linha por linha até o final do arquivo
			while ((line = br.readLine()) != null) {
				content.append(line).append("\n");
			}

			// Define o texto do JTextArea com o conteúdo lido
			jTextAreaPreviewCode.setText(content.toString());
			br.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public void saida() {
		// Exibe uma caixa de diálogo com uma mensagem de aviso indicando que o programa
		// será encerrado.
		JOptionPane.showMessageDialog(null,
				"Voce pressionou o botao 'Cancelar'. O programa sera encerrado.",
				null, JOptionPane.WARNING_MESSAGE, this.saidaIcon);
	}

	private void olt() {
		// Carrega os ícones necessários para o diálogo
		final ClassLoader classLoader = OltGpon.class.getClassLoader();
		this.errorIcon = new ImageIcon(classLoader.getResource("erro.png"));
		this.successIcon = new ImageIcon(classLoader.getResource("success.png"));
		this.saidaIcon = new ImageIcon(classLoader.getResource("saida.png"));
		this.nomeArq = "scriptAN5k.txt";
		this.fileChooserIsSelected = false;

		this.cpeType = new String[] {
				"SFU",
				"HGU",
				"BOX MDU",
				"CARD MDU",
				"DPU"
		};

		this.ponType = new String[] {
				"1G EPON",
				"10G EPON 10G/10G",
				"10G EPON 1G/10G",
				"1G GPON",
				"10 GPON 2.5G/10G",
				"10GPON 10G/10G",
				"GPON/XGPON/XGSPON auto",
				"EPON/10GEPON auto",
				"25G PON 25G/25G"
		};

		this.wifiNumber = new String[] {
				"0",
				"1",
				"2",
				"3",
				"4"
		};

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		olt();

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jPasswordFieldOltPasswd = new javax.swing.JPasswordField();
		jTextFieldOltUser = new javax.swing.JTextField();
		jTextFieldIpOlt = new javax.swing.JTextField();
		jFormattedTextFieldPortOlt = new javax.swing.JFormattedTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jSpinnerSlotPON = new javax.swing.JSpinner(this.model);
		jSpinnerPortaPon = new javax.swing.JSpinner(this.model2);
		jSpinnerSlotCpe = new javax.swing.JSpinner(this.model3);
		// jTextFieldPortaPon = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		// jTextFieldSlotPON = new javax.swing.JTextField();
		jTextFieldPhyIdCPE = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		// jTextFieldPortaPon1 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextFieldModeloONU = new javax.swing.JTextField();
		jCheckBoxFlagONUCapability = new javax.swing.JCheckBox();
		jButtonCriarONUCapability = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jLabel16 = new javax.swing.JLabel();
		jTextFieldSSID5 = new javax.swing.JTextField();
		jTextFieldPassPPPOE = new javax.swing.JTextField();
		jTextFieldUserPPPOE = new javax.swing.JTextField();
		jTextFieldVlanPPPOE = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jTextFieldSSIDPass5 = new javax.swing.JTextField();
		jLabel18 = new javax.swing.JLabel();
		jTextFieldSSIDPass2 = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		jTextFieldSSID2 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jRadioButtonBridge = new javax.swing.JRadioButton();
		jRadioButtonRouter = new javax.swing.JRadioButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel15 = new javax.swing.JLabel();
		jButtonFileChooser = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jButtonEnviar = new javax.swing.JButton();
		jButtonCriar = new javax.swing.JButton();
		jButtonCancel = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jScrollPanel = new javax.swing.JScrollPane();
		jTextAreaPreviewCode = new javax.swing.JTextArea();

		setBackground(new java.awt.Color(204, 204, 204));
		setClosable(false);
		setForeground(java.awt.Color.darkGray);
		setIconifiable(true);
		setMaximizable(true);
		setResizable(true);
		setTitle("AN5000");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		// setFrameIcon(new
		// javax.swing.ImageIcon(getClass().getResource("/assets/OLT_AN6000.png"))); //
		setMinimumSize(new java.awt.Dimension(907, 800));
		setPreferredSize(new java.awt.Dimension(907, 800));
		setRequestFocusEnabled(false);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Dados de acesso da OLT ",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("JetBrains Mono ExtraBold", 0, 12))); // NOI18N
		jPanel1.setToolTipText("OLT");
		jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jLabel1.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12));
		jLabel1.setText("IP OLT");

		jLabel2.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
		jLabel2.setText("Usuario");

		jLabel9.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
		jLabel9.setText("Porta");

		jLabel10.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
		jLabel10.setText("Senha");

		jPasswordFieldOltPasswd.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPasswordFieldOltPasswdActionPerformed(evt);
			}
		});

		jTextFieldOltUser.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldOltUserActionPerformed(evt);
			}
		});

		jTextFieldIpOlt.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldIpOltActionPerformed(evt);
			}
		});

		jFormattedTextFieldPortOlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));
		jFormattedTextFieldPortOlt.setToolTipText("porta");
		jFormattedTextFieldPortOlt.setName("porta"); // NOI18N
		jFormattedTextFieldPortOlt.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jFormattedTextFieldPortOltActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel1Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1)
										.addComponent(jLabel9))
								.addGap(12, 12, 12)
								.addGroup(jPanel1Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
										.addComponent(jTextFieldIpOlt,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												285,
												Short.MAX_VALUE)
										.addComponent(jFormattedTextFieldPortOlt))
								.addGap(153, 153, 153)
								.addGroup(jPanel1Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
										.addComponent(jLabel10,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
										.addComponent(jTextFieldOltUser)
										.addComponent(jPasswordFieldOltPasswd,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												285, Short.MAX_VALUE))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(jLabel2)
										.addComponent(jTextFieldOltUser,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextFieldIpOlt,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel9)
										.addComponent(jLabel10)
										.addComponent(jPasswordFieldOltPasswd,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jFormattedTextFieldPortOlt,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(6, 6, 6)));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Formulario do Script ",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("JetBrains Mono ExtraBold", 0, 12))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel3.setText("Phy-ID CPE:");

		jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel4.setText("Porta PON:");

		// jSpinnerPortaPon.addActionListener(new java.awt.event.ActionListener() {
		// public void actionPerformed(java.awt.event.ActionEvent evt) {
		// jTextFieldPortaPonActionPerformed(evt);
		// }
		// });

		jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel5.setText("Slot GPON:");

		// jSpinnerSlotPON.addActionListener(new java.awt.event.ActionListener() {
		// public void actionPerformed(java.awt.event.ActionEvent evt) {
		// jTextFieldSlotPONActionPerformed(evt);
		// }
		// });

		jTextFieldPhyIdCPE.setText("FHTT12345678");
		jTextFieldPhyIdCPE.setToolTipText("FHTT12345678");
		jTextFieldPhyIdCPE.setName("FHTT12345678"); // NOI18N
		jTextFieldPhyIdCPE.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldPhyIdCPEActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel7.setText("Slot CPE:");

		// jSpinnerSlotCpe.addActionListener(new java.awt.event.ActionListener() {
		// public void actionPerformed(java.awt.event.ActionEvent evt) {
		// jTextFieldPortaPon1ActionPerformed(evt);
		// }
		// });

		jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel6.setText("Modelo CPE:");

		jTextFieldModeloONU.setText("HG6145F3");
		jTextFieldModeloONU.setToolTipText("FHTT12345678");
		jTextFieldModeloONU.setName("FHTT12345678"); // NOI18N
		jTextFieldModeloONU.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldModeloONUActionPerformed(evt);
			}
		});

		jCheckBoxFlagONUCapability.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jCheckBoxFlagONUCapability.setText("Criar ONU Capability");
		jCheckBoxFlagONUCapability.setVisible(true);
		jCheckBoxFlagONUCapability.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxFlagONUCapabilityActionPerformed(evt);
			}
		});

		jButtonCriarONUCapability.setText("Criar");
		jButtonCriarONUCapability.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCriarONUCapabilityActionPerformed(evt);
			}
		});

		jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados para WAN Service",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Dialog", 1, 11))); // NOI18N

		jLabel16.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel16.setText("SSID 2.4Ghz:");

		jTextFieldSSID5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldSSID5ActionPerformed(evt);
			}
		});

		jTextFieldPassPPPOE.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldPassPPPOEActionPerformed(evt);
			}
		});

		jTextFieldUserPPPOE.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldUserPPPOEActionPerformed(evt);
			}
		});

		jTextFieldVlanPPPOE.setToolTipText("FHTT12345678");
		jTextFieldVlanPPPOE.setName("FHTT12345678"); // NOI18N
		jTextFieldVlanPPPOE.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldVlanPPPOEActionPerformed(evt);
			}
		});

		jLabel14.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel14.setText("SSID 5Ghz:");

		jLabel13.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel13.setText("Senha PPPOE:");

		jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel12.setText("User PPPOE:");

		jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel11.setText("Vlan PPPOE:");

		jTextFieldSSIDPass5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldSSIDPass5ActionPerformed(evt);
			}
		});

		jLabel18.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel18.setText("Senha 5Ghz:");

		jTextFieldSSIDPass2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldSSIDPass2ActionPerformed(evt);
			}
		});

		jLabel17.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel17.setText("Senha 2.4Ghz:");

		jTextFieldSSID2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldSSID2ActionPerformed(evt);
			}
		});

		jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
		jLabel8.setText("CPE em:");

		buttonGroup1.add(jRadioButtonBridge);
		jRadioButtonBridge.setSelected(true);
		jRadioButtonBridge.setText("VEIP");
		jRadioButtonBridge.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jRadioButtonBridge.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jRadioButtonBridge.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButtonBridgeActionPerformed(evt);
			}
		});

		buttonGroup1.add(jRadioButtonRouter);
		jRadioButtonRouter.setText("WAN-SERVICE");
		jRadioButtonRouter.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jRadioButtonRouter.setMargin(new java.awt.Insets(0, 0, 0, 0));
		jRadioButtonRouter.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButtonRouterActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel6Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel6Layout
												.createSequentialGroup()
												.addGroup(jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jLabel13,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																100,
																Short.MAX_VALUE)
														.addComponent(jLabel11,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(jLabel12,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jTextFieldVlanPPPOE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																127,
																Short.MAX_VALUE)
														.addComponent(jTextFieldUserPPPOE)
														.addComponent(jTextFieldPassPPPOE)))
										.addGroup(jPanel6Layout
												.createSequentialGroup()
												.addGap(12, 12, 12)
												.addComponent(jRadioButtonBridge)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jRadioButtonRouter))
										.addComponent(jLabel8))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel6Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
										.addComponent(jLabel18,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel14,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel16,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel17))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel6Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
										.addComponent(jTextFieldSSID5,
												javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextFieldSSIDPass2,
												javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextFieldSSID2,
												javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextFieldSSIDPass5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												200,
												javax.swing.GroupLayout.PREFERRED_SIZE))));
		jPanel6Layout.setVerticalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup()
								.addGroup(jPanel6Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel6Layout
												.createSequentialGroup()
												.addGroup(jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel11,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextFieldVlanPPPOE,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(7, 7, 7)
												.addGroup(jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel12,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextFieldUserPPPOE)))
										.addGroup(jPanel6Layout
												.createSequentialGroup()
												.addGroup(jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel16,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextFieldSSID2))
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel17,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextFieldSSIDPass2))))
								.addGap(6, 6, 6)
								.addGroup(jPanel6Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel13,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												23,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextFieldPassPPPOE)
										.addComponent(jLabel14,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												23,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextFieldSSID5))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel6Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel6Layout
												.createSequentialGroup()
												.addComponent(jLabel8)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jRadioButtonBridge)
														.addComponent(jRadioButtonRouter)))
										.addGroup(jPanel6Layout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel18,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														23,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextFieldSSIDPass5)))));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGap(6, 6, 6)
								.addGroup(jPanel2Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
										.addComponent(jLabel7,
												javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel4,
												javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel5,
												javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel3,
												javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel6,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												110,
												Short.MAX_VALUE))
								.addGap(30, 30, 30)
								.addGroup(jPanel2Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jTextFieldModeloONU,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												116,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(
												jSpinnerSlotCpe,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												116,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(
												jSpinnerSlotPON,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												116,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(
												jSpinnerPortaPon,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												116,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextFieldPhyIdCPE,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												116,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout
												.createSequentialGroup()
												.addGap(363, 363, 363)
												.addComponent(jCheckBoxFlagONUCapability)
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jButtonCriarONUCapability))
										.addGroup(jPanel2Layout
												.createSequentialGroup()
												.addGap(18, 18, 18)
												.addComponent(jPanel6,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
								.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jPanel6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel2Layout
												.createSequentialGroup()
												.addGap(4, 4, 4)
												.addGroup(jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextFieldPhyIdCPE,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(7, 7, 7)
												.addGroup(jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jSpinnerSlotPON))
												.addGap(6, 6, 6)
												.addGroup(jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jSpinnerPortaPon))
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jSpinnerSlotCpe))
												.addGap(4, 4, 4)
												.addGroup(jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextFieldModeloONU,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(2, 2, 2)
								.addGroup(jPanel2Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButtonCriarONUCapability)
										.addComponent(jCheckBoxFlagONUCapability))
								.addGap(2, 2, 2)));

		jTextFieldPhyIdCPE.getAccessibleContext().setAccessibleName("FHTT12345678");
		jTextFieldPhyIdCPE.getAccessibleContext().setAccessibleParent(jLabel3);
		jTextFieldModeloONU.getAccessibleContext().setAccessibleName("HG6145F3");

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Script pronto",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("JetBrains Mono ExtraBold", 0, 12))); // NOI18N
		jPanel3.setToolTipText("OLT");
		jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jLabel15.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
		jLabel15.setText("Importar Script");

		jButtonFileChooser.setText("File");
		jButtonFileChooser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonFileChooserActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel15)
								.addGap(80, 80, 80)
								.addComponent(jButtonFileChooser,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										140,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(12, 12, 12)));
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addGroup(jPanel3Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButtonFileChooser)
										.addComponent(jLabel15))
								.addGap(0, 0, 0)));

		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comandos",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("JetBrains Mono ExtraBold", 0, 12))); // NOI18N
		jPanel4.setVerifyInputWhenFocusTarget(false);

		jButtonEnviar.setText("Enviar");
		jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonEnviarActionPerformed(evt);
			}
		});

		jButtonCriar.setText("Criar");
		jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCriarActionPerformed(evt);
			}
		});

		jButtonCancel.setText("Cancel");
		jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCancelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel4Layout.createSequentialGroup()
										.addGap(71, 71, 71)
										.addComponent(jButtonEnviar)
										.addGap(14, 14, 14)
										.addComponent(jButtonCriar)
										.addGap(14, 14, 14)
										.addComponent(jButtonCancel)
										.addContainerGap()));
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addGroup(jPanel4Layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButtonEnviar)
										.addComponent(jButtonCriar)
										.addComponent(jButtonCancel))
								.addGap(0, 0, Short.MAX_VALUE)));

		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preview",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("JetBrains Mono ExtraBold", 0, 12))); // NOI18N

		jTextAreaPreviewCode.setEditable(false);
		jTextAreaPreviewCode.setColumns(20);
		jTextAreaPreviewCode.setRows(5);
		jScrollPanel.setViewportView(jTextAreaPreviewCode);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel5Layout.createSequentialGroup()
										.addContainerGap()
										.addComponent(jScrollPanel)
										.addContainerGap()));
		jPanel5Layout.setVerticalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250,
								javax.swing.GroupLayout.PREFERRED_SIZE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.TRAILING,
										false)
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
												layout
														.createSequentialGroup()
														.addComponent(jPanel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(jPanel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jPanel2,
												javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												0, Short.MAX_VALUE)
										.addComponent(jPanel1,
												javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												870,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jPanel5,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jPanel4,
												javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jPanel3,
												javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel5,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jPasswordFieldOltPasswdActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldIpOltActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jFormattedTextFieldPortOltActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonFileChooserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonFileChooserActionPerformed
		JFileChooser fileChooser = new JFileChooser();

		// Adiciona um filtro para aceitar apenas arquivos de texto e derivados
		FileNameExtensionFilter filter = new FileNameExtensionFilter(
				"Arquivos de Texto", "txt", "md", "csv", "log", "java", "xml", "html", "json");
		fileChooser.setFileFilter(filter);
		// Exibe o seletor de arquivo e obtém a resposta do usuário
		int returnValue = fileChooser.showOpenDialog(this);
		fileChooser.setDialogTitle("Selecione o arquivo:");
		fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

		// Verifica se o usuário escolheu um arquivo
		if (returnValue == JFileChooser.APPROVE_OPTION) {
			this.fileChooserIsSelected = true;
			// Obtém o arquivo selecionado
			java.io.File selectedFile = fileChooser.getSelectedFile();
			System.out.println("Arquivo selecionado: " + selectedFile.getAbsolutePath());
			this.nomeArq = selectedFile.getAbsolutePath();
			jButtonFileChooser.setText(selectedFile.getName());
			previewText();
		} else {
			this.fileChooserIsSelected = false;
			JOptionPane.showMessageDialog(null,
					"Nenhum arquivo selecionado.", "Error!",
					JOptionPane.ERROR_MESSAGE, this.errorIcon);
			jButtonFileChooser.setText("File");
			jTextAreaPreviewCode.setText("");
		}

	}// GEN-LAST:event_jButtonFileChooserActionPerformed

	private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEnviarActionPerformed
		if (this.fileChooserIsSelected) {
			if (this.oltGponAN5k.checkTelnet(jTextFieldIpOlt.getText(), jFormattedTextFieldPortOlt.getText(),
					jTextFieldOltUser.getText(), jPasswordFieldOltPasswd.getPassword(),
					this.errorIcon)) {
				JOptionPane.showMessageDialog(null,
						"Valores validos!", "Sucesso!",
						JOptionPane.ERROR_MESSAGE, this.successIcon);

				Telnet acessoOlt = new Telnet(jTextFieldIpOlt.getText(),
						Integer.parseInt(jFormattedTextFieldPortOlt.getText()),
						jTextFieldOltUser.getText(),
						new String(jPasswordFieldOltPasswd.getPassword()));
				acessoOlt.oltAccess(this.nomeArq);
			}
		} else {
			JOptionPane.showMessageDialog(null,
					"Nenhum arquivo selecionado ou criado!", "Error",
					JOptionPane.ERROR_MESSAGE, this.errorIcon);
		}
	}// GEN-LAST:event_jButtonEnviarActionPerformed

	private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {
		this.nomeArq = "scriptAN5k.txt";

		if (this.oltGponAN5k.start(nomeArq)) {
			// Cria um objeto ConfigGenerator para gerar o script de configuração
			JOptionPane.showMessageDialog(null,
					"Script criado com sucesso!", "Sucesso!",
					JOptionPane.ERROR_MESSAGE, this.successIcon);
			this.fileChooserIsSelected = true;
			jButtonFileChooser.setText(this.nomeArq);
			previewText();

		} else {
			JOptionPane.showMessageDialog(null,
					"Script nao foi criado!", "Error!",
					JOptionPane.ERROR_MESSAGE, this.errorIcon);
		}
	}

	private void jTextFieldOltUserActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		capa.dispose();
	}

	private void jTextFieldSSIDPass5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldSSIDPass2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldSSID2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldSSID5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldPassPPPOEActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldUserPPPOEActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldVlanPPPOEActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonCriarONUCapabilityActionPerformed(java.awt.event.ActionEvent evt) {
		// capa.setVisible(true);
		// capa.setListener(this); // Define o OltAN5k como o listener
		JPanel glassPane = (JPanel) this.getRootPane().getGlassPane();
		glassPane.setVisible(true);
		glassPane.setOpaque(false);

		glassPane.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				playAlertSound();
			}
		});
		glassPane.addMouseListener(new java.awt.event.MouseAdapter() {
		});

		capa.setListener(this);
		capa.addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosed(java.awt.event.WindowEvent e) {
				glassPane.setVisible(false); // Desbloqueia a interação
			}
		});
		capa.setVisible(true);
	}

	private void playAlertSound() {
		try {
			AudioInputStream audioInputStream = AudioSystem
					.getAudioInputStream(getClass().getResource("/sounds/error1.wav"));
			Clip clip = AudioSystem.getClip();
			clip.open(audioInputStream);
			clip.start();
			audioInputStream.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@Override
	public void onProfileCreated(String cpeType, String ponType, String wifiNumber,
			String tenGPort, String oneGPort, String equipamentID,
			String potsNumber, String profileName, String usbNumber) {

		if (this.jCheckBoxFlagONUCapability.isSelected()) {
			// Aqui você pode atualizar os componentes ou processar os dados recebidos
			this.jTextFieldModeloONU.setText(profileName);

			System.out.println("Dados recebidos:");
			System.out.println("CPE Type: " + cpeType);
			System.out.println("PON Type: " + ponType);
			System.out.println("WiFi Number: " + wifiNumber);
			System.out.println("10G Port: " + tenGPort);
			System.out.println("1G Port: " + oneGPort);
			System.out.println("Equipament ID: " + equipamentID);
			System.out.println("POTS Number: " + potsNumber);
			System.out.println("Profile Name: " + profileName);
			System.out.println("USB Number: " + usbNumber);

		}
	}

	private void jCheckBoxFlagONUCapabilityActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldModeloONUActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldPortaPon1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldPhyIdCPEActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}
	// TODO add your handling code here:

	private void jTextFieldSlotPONActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldPortaPonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jRadioButtonBridgeActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void jRadioButtonRouterActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButtonCancel;
	private javax.swing.JButton jButtonCriar;
	private javax.swing.JButton jButtonCriarONUCapability;
	private javax.swing.JButton jButtonEnviar;
	private javax.swing.JButton jButtonFileChooser;
	private javax.swing.JCheckBox jCheckBoxFlagONUCapability;
	private javax.swing.JFormattedTextField jFormattedTextFieldPortOlt;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPasswordField jPasswordFieldOltPasswd;
	private javax.swing.JRadioButton jRadioButtonBridge;
	private javax.swing.JRadioButton jRadioButtonRouter;
	private javax.swing.JScrollPane jScrollPanel;
	private javax.swing.JTextArea jTextAreaPreviewCode;
	private javax.swing.JTextField jTextFieldIpOlt;
	private javax.swing.JTextField jTextFieldModeloONU;
	private javax.swing.JTextField jTextFieldOltUser;
	private javax.swing.JTextField jTextFieldPassPPPOE;
	private javax.swing.JTextField jTextFieldPhyIdCPE;
	private javax.swing.JTextField jTextFieldSSID2;
	private javax.swing.JTextField jTextFieldSSID5;
	private javax.swing.JTextField jTextFieldSSIDPass2;
	private javax.swing.JTextField jTextFieldSSIDPass5;
	private javax.swing.JTextField jTextFieldUserPPPOE;
	private javax.swing.JTextField jTextFieldVlanPPPOE;

	private SpinnerNumberModel model;
	private SpinnerNumberModel model2;
	private SpinnerNumberModel model3;

	private javax.swing.JSpinner jSpinnerPortaPon;
	private javax.swing.JSpinner jSpinnerSlotCpe;
	private javax.swing.JSpinner jSpinnerSlotPON;

	private CapabilityProfile capa;

	private String[] cpeType;
	private String[] ponType;
	private String[] wifiNumber;
	private boolean fileChooserIsSelected;
	private String nomeArq;
	private ImageIcon errorIcon;
	private ImageIcon successIcon;
	private ImageIcon saidaIcon;
	private final OltGponAN5k oltGponAN5k;
	// End of variables declaration
}
