package engtelecom.swingType;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author faber222
 */
public class OltGponMenu extends JFrame {

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private ButtonGroup buttonGroup1;

        private JButton jButtonCancel;

        private JButton jButtonCriar;

        private JButton jButtonEnviar;

        private JComboBox<String> jComboBoxInterfaceUplink;

        private JComboBox<String> jComboBoxModoAutoConfig;

        private JLabel jLabel1;

        private JLabel jLabel10;

        private JLabel jLabel2;

        private JLabel jLabel3;

        private JLabel jLabel4;

        private JLabel jLabel5;

        private JLabel jLabel6;

        private JLabel jLabel7;

        private JLabel jLabel8;
        private JLabel jLabel9;
        private JPanel jPanel1;
        private JPanel jPanel2;
        private JPasswordField jPasswordFieldOltPasswd;
        private JRadioButton jRadioButtonBridge;
        private JRadioButton jRadioButtonRouter;
        private JTextField jTextFieldIpOlt;
        private JTextField jTextFieldOltUser;
        private JTextField jTextFieldPortOlt;
        private JTextField jTextFieldRangeProfileLine;
        private JTextField jTextFieldRangeProfileVlan;
        private JTextField jTextFieldRangeVlan;
        private String ipOlt;

        /**
         * Creates new form OltGponMenu
         */
        public OltGponMenu() {
                initComponents();
        }

        /**
         * @param args the command line arguments
         */
        public void start() {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(OltGponMenu.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(OltGponMenu.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(OltGponMenu.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(OltGponMenu.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new OltGponMenu().setVisible(true);
                        }
                });
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new ButtonGroup();
                jButtonCancel = new JButton();
                jButtonCriar = new JButton();
                jPanel1 = new JPanel();
                jLabel1 = new JLabel();
                jLabel2 = new JLabel();
                jTextFieldIpOlt = new JTextField(20);
                jLabel9 = new JLabel();
                jLabel10 = new JLabel();
                jPasswordFieldOltPasswd = new JPasswordField();
                jTextFieldOltUser = new JTextField();
                jTextFieldPortOlt = new JTextField();
                jPanel2 = new JPanel();
                jLabel7 = new JLabel();
                jRadioButtonBridge = new JRadioButton();
                jRadioButtonRouter = new JRadioButton();
                jComboBoxInterfaceUplink = new JComboBox<>();
                jLabel3 = new JLabel();
                jLabel4 = new JLabel();
                jComboBoxModoAutoConfig = new JComboBox<>();
                jLabel6 = new JLabel();
                jLabel8 = new JLabel();
                jTextFieldRangeProfileVlan = new JTextField();
                jTextFieldRangeProfileLine = new JTextField();
                jLabel5 = new JLabel();
                jTextFieldRangeVlan = new JTextField();
                jButtonEnviar = new JButton();

                setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("OLT-AUTO-CONFIG");
                setFont(new java.awt.Font("JetBrains Mono", 0, 10)); // NOI18N
                setResizable(false);

                jButtonCancel.setText("Cancel");

                jButtonCriar.setText("Criar");
                jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCriarActionPerformed(evt);
                        }
                });

                jPanel1.setBorder(BorderFactory.createTitledBorder(null, " Dados de acesso da OLT ",
                                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                                new java.awt.Font("JetBrains Mono ExtraBold", 0, 12))); // NOI18N
                jPanel1.setToolTipText("OLT");
                jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                jLabel1.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
                jLabel1.setText("IP OLT");

                jLabel2.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
                jLabel2.setText("Usuario");

                jTextFieldIpOlt.setText("IP");
                jTextFieldIpOlt.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldIpOltActionPerformed(evt);
                        }
                });

                jLabel9.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
                jLabel9.setText("Porta");

                jLabel10.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
                jLabel10.setText("Senha");

                jPasswordFieldOltPasswd.setText("Password");
                jPasswordFieldOltPasswd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jPasswordFieldOltPasswdActionPerformed(evt);
                        }
                });

                jTextFieldOltUser.setText("User");

                jTextFieldPortOlt.setText("Port");
                jTextFieldPortOlt.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldPortOltActionPerformed(evt);
                        }
                });

                GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(jLabel9))
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jTextFieldPortOlt)
                                                                                .addComponent(jTextFieldIpOlt))
                                                                .addGap(35, 35, 35)
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                GroupLayout.Alignment.TRAILING,
                                                                                                false)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel2,
                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addPreferredGap(
                                                                                                                LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jTextFieldOltUser,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                357,
                                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel10,
                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGap(26, 26, 26)
                                                                                                .addComponent(jPasswordFieldOltPasswd,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                357,
                                                                                                                GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(jTextFieldIpOlt,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jTextFieldOltUser,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel9)
                                                                                .addComponent(jLabel10)
                                                                                .addComponent(jPasswordFieldOltPasswd,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextFieldPortOlt,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jPanel2.setBorder(BorderFactory.createTitledBorder(null, " Formulario do Script ",
                                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                                new java.awt.Font("JetBrains Mono ExtraBold", 0, 12))); // NOI18N

                jLabel7.setText("CPEs de terceiros, em:");

                buttonGroup1.add(jRadioButtonBridge);
                jRadioButtonBridge.setSelected(true);
                jRadioButtonBridge.setText("BRIDGE");
                jRadioButtonBridge.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                jRadioButtonBridge.setMargin(new java.awt.Insets(0, 0, 0, 0));
                jRadioButtonBridge.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioButtonBridgeActionPerformed(evt);
                        }
                });

                buttonGroup1.add(jRadioButtonRouter);
                jRadioButtonRouter.setText("ROUTER");
                jRadioButtonRouter.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                jRadioButtonRouter.setMargin(new java.awt.Insets(0, 0, 0, 0));
                jRadioButtonRouter.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioButtonRouterActionPerformed(evt);
                        }
                });

                jComboBoxInterfaceUplink.setMaximumRowCount(6);
                jComboBoxInterfaceUplink.setModel(
                                new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                jComboBoxInterfaceUplink.setMinimumSize(new java.awt.Dimension(65, 23));
                jComboBoxInterfaceUplink.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBoxInterfaceUplinkActionPerformed(evt);
                        }
                });

                jLabel3.setText("Interface Uplink");

                jLabel4.setText("Range Profile Line");

                jComboBoxModoAutoConfig.setMaximumRowCount(3);
                jComboBoxModoAutoConfig.setModel(
                                new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                jComboBoxModoAutoConfig.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBoxModoAutoConfigActionPerformed(evt);
                        }
                });

                jLabel6.setText("Modo do Auto-Config");

                jLabel8.setText("Range Profile Vlan");

                jTextFieldRangeProfileVlan.setText("jTextField2");
                jTextFieldRangeProfileVlan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldRangeProfileVlanActionPerformed(evt);
                        }
                });

                jTextFieldRangeProfileLine.setText("jTextField2");
                jTextFieldRangeProfileLine.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldRangeProfileLineActionPerformed(evt);
                        }
                });

                jLabel5.setText("Range Vlan");

                jTextFieldRangeVlan.setText("jTextField2");
                jTextFieldRangeVlan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldRangeVlanActionPerformed(evt);
                        }
                });

                GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel4,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                137,
                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jTextFieldRangeProfileLine,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                230,
                                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(GroupLayout.Alignment.TRAILING,
                                                                                                jPanel2Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel5,
                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addPreferredGap(
                                                                                                                                LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(jTextFieldRangeVlan,
                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                231,
                                                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(GroupLayout.Alignment.TRAILING,
                                                                                                jPanel2Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel3,
                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                137,
                                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(jComboBoxInterfaceUplink,
                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                230,
                                                                                                                                GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(38, 38, 38)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                GroupLayout.Alignment.TRAILING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel6,
                                                                                                                                GroupLayout.Alignment.LEADING,
                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                137,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel8,
                                                                                                                                GroupLayout.Alignment.LEADING,
                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jComboBoxModoAutoConfig,
                                                                                                                                0,
                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jTextFieldRangeProfileVlan,
                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                269,
                                                                                                                                Short.MAX_VALUE)))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(12, 12, 12)
                                                                                                                                .addComponent(jRadioButtonBridge)
                                                                                                                                .addPreferredGap(
                                                                                                                                                LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jRadioButtonRouter))
                                                                                                                .addComponent(jLabel7))
                                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(5, 5, 5)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createParallelGroup(
                                                                                                                GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jComboBoxModoAutoConfig)
                                                                                                .addComponent(jLabel6,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                23,
                                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createParallelGroup(
                                                                                                                GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel3,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                23,
                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jComboBoxInterfaceUplink,
                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))
                                                                .addGap(12, 12, 12)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel8,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                23,
                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextFieldRangeProfileVlan,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel5,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                23,
                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextFieldRangeVlan,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createParallelGroup(
                                                                                                                GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel4,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                23,
                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jTextFieldRangeProfileLine,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel7)
                                                                                                .addPreferredGap(
                                                                                                                LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jRadioButtonBridge)
                                                                                                                .addComponent(jRadioButtonRouter))))
                                                                .addGap(12, 12, 12)));

                jButtonEnviar.setText("Enviar");
                jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonEnviarActionPerformed(evt);
                        }
                });

                GroupLayout layout = new GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(jButtonEnviar)
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(jButtonCriar)
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(jButtonCancel))
                                                                                .addComponent(jPanel1,
                                                                                                GroupLayout.Alignment.LEADING,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel2,
                                                                                                GroupLayout.Alignment.LEADING,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(21, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE,
                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE,
                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                                                12,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButtonCancel)
                                                                                .addComponent(jButtonCriar)
                                                                                .addComponent(jButtonEnviar))
                                                                .addGap(12, 12, 12)));

                jPanel1.getAccessibleContext().setAccessibleName("OLT");

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jComboBoxInterfaceUplinkActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxInterfaceUplinkActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jComboBoxInterfaceUplinkActionPerformed

        private void jRadioButtonRouterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonRouterActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jRadioButtonRouterActionPerformed

        private void jRadioButtonBridgeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonBridgeActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jRadioButtonBridgeActionPerformed

        private void jTextFieldRangeProfileVlanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldRangeProfileVlanActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextFieldRangeProfileVlanActionPerformed

        private void jTextFieldRangeProfileLineActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldRangeProfileLineActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextFieldRangeProfileLineActionPerformed

        private void jTextFieldRangeVlanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldRangeVlanActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextFieldRangeVlanActionPerformed

        private void jTextFieldIpOltActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldPortOltActionPerformed
                //ipOlt = jTextFieldIpOlt.getText();
                //System.out.println(ipOlt);
        }// GEN-LAST:event_jTextFieldPortOltActionPerformed

        private void jTextFieldPortOltActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldPortOltActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextFieldPortOltActionPerformed

        private void jPasswordFieldOltPasswdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jPasswordFieldOltPasswdActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jPasswordFieldOltPasswdActionPerformed

        private void jComboBoxModoAutoConfigActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxModoAutoConfigActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jComboBoxModoAutoConfigActionPerformed

        private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEnviarActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButtonEnviarActionPerformed

        private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCriarActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButtonCriarActionPerformed

        // End of variables declaration//GEN-END:variables
}
