/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package engtelecom;

import javax.swing.ImageIcon;

import engtelecom.product.OltGpon;
import engtelecom.swingType.InfoFrame;
import engtelecom.swingType.Olt8820;
import engtelecom.swingType.OltAN5k;
import engtelecom.swingType.OltG08;
import engtelecom.swingType.OltG16;

/**
 *
 * @author faber222
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form OltGponMenu
     */
    public App() {
        initComponents();
        this.setIconImage(this.mainIcon.getImage());
    }

    private void olt() {
        // Carrega os ícones necessários para o diálogo
        final ClassLoader classLoader = OltGpon.class.getClassLoader();
        this.olt8820Icon = new ImageIcon(classLoader.getResource("OLT_8820.png"));
        this.oltG16Icon = new ImageIcon(classLoader.getResource("OLT_G08.png"));
        this.oltG08Icon = new ImageIcon(classLoader.getResource("OLT_G08.png"));
        this.oltAN6KIcon = new ImageIcon(classLoader.getResource("OLT_AN6000.png"));
        this.terminalIcon = new ImageIcon(classLoader.getResource("icons/application_xp_terminal.png"));
        this.infoIcon = new ImageIcon(classLoader.getResource("icons/information.png"));
        this.infoMainIcon = new ImageIcon(classLoader.getResource("icons/help.png"));
        this.mainIcon = new ImageIcon(classLoader.getResource("icons/bricks.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        olt();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAN5k = new javax.swing.JMenuItem();
        jMenuG16 = new javax.swing.JMenuItem();
        jMenuG08 = new javax.swing.JMenuItem();
        jMenu8820i = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HefForge OLT - Script tools");
        setFont(new java.awt.Font("JetBrains Mono", 0, 10)); // NOI18N

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
                jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1165, Short.MAX_VALUE));
        jDesktopPaneLayout.setVerticalGroup(
                jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 696, Short.MAX_VALUE));

        jMenu1.setIcon(terminalIcon); // NOI18N
        jMenu1.setText("OLT");

        jMenuAN5k.setIcon(oltAN6KIcon); // NOI18N
        jMenuAN5k.setText("AN5000");
        jMenuAN5k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAN5kActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAN5k);

        jMenuG16.setIcon(oltG16Icon); // NOI18N
        jMenuG16.setText("G16");
        jMenuG16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuG16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuG16);

        jMenuG08.setIcon(oltG08Icon); // NOI18N
        jMenuG08.setText("G08");
        jMenuG08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuG08ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuG08);

        jMenu8820i.setIcon(olt8820Icon); // NOI18N
        jMenu8820i.setText("8820i");
        jMenu8820i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8820iActionPerformed(evt);
            }
        });
        jMenu1.add(jMenu8820i);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(infoIcon); // NOI18N
        jMenu2.setText("Sobre");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuInfo.setIcon(
                infoMainIcon); // NOI18N
        jMenuInfo.setText("Info");
        jMenuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInfoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuInfo);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDesktopPane));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDesktopPane));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuG16ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuG16ActionPerformed
        // TODO add your handling code here:
        OltG16 telaG16 = new OltG16();
        jDesktopPane.add(telaG16);
        telaG16.setVisible(true);
    }// GEN-LAST:event_jMenuG16ActionPerformed

    private void jMenuG08ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuG08ActionPerformed
        OltG08 telaG08 = new OltG08();
        jDesktopPane.add(telaG08);
        telaG08.setVisible(true);
    }// GEN-LAST:event_jMenuG08ActionPerformed

    private void jMenu8820iActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenu8820iActionPerformed
        Olt8820 tela8820 = new Olt8820();
        jDesktopPane.add(tela8820);
        tela8820.setVisible(true);
    }// GEN-LAST:event_jMenu8820iActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {
        InfoFrame info = new InfoFrame();
        info.setVisible(true);
    }

    private void jMenuInfoActionPerformed(java.awt.event.ActionEvent evt) {
        new InfoFrame().setVisible(true);
    }

    private void jMenuAN5kActionPerformed(java.awt.event.ActionEvent evt) {
        OltAN5k telaAN5000 = new OltAN5k();
        jDesktopPane.add(telaAN5000);
        telaAN5000.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenu8820i;
    private javax.swing.JMenuItem jMenuAN5k;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuG08;
    private javax.swing.JMenuItem jMenuG16;
    private javax.swing.JMenuItem jMenuInfo;
    private ImageIcon infoIcon;
    private ImageIcon infoMainIcon;
    private ImageIcon terminalIcon;
    private ImageIcon olt8820Icon;
    private ImageIcon oltG16Icon;
    private ImageIcon oltG08Icon;
    private ImageIcon oltAN6KIcon;
    private ImageIcon mainIcon;

    // End of variables declaration//GEN-END:variables
}
